default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=3300']
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args:
          - --line-length=88
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.2
    hooks:
    -   id: bandit
        exclude: ^tests/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
    -   id: mypy
        args: [--strict, --ignore-missing-imports]
        exclude: ^tests/
-   repo: https://github.com/pycqa/pylint
    rev: v2.13.4
    hooks:
    -   id: pylint
        language: system
